# Generated by Django 6.1 on 2026-08-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('opponent', models.CharField(max_length=100)),
                ('is_home', models.BooleanField()),
                ('location', models.CharField(max_length=100)),
                ('goals_for', models.PositiveIntegerField(blank=True, null=True)),
                ('goals_against', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
