# Generated by Django 6.1 on 2026-08-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_training_end_time_training_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
